### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by 9x3l6** [fastapi-mvc/fastapi-mvc#313]
- [X] I have searched the [issues](https://github.com/fastapi-mvc/fastapi-mvc/issues) of this repo and believe that this is not a duplicate.

**Describe the bug**

Fails to successfully create new project

**Expected behavior**

Should create new project when running `fastapi-mvc new videos-api`
**To Reproduce**

```sh
fastapi-mvc new videos-api
```
**Environment**
* Python version: 3.11.4
* Operating System and version: Mac Monterey 12.6.8
* fastapi-mvc version: 0.28.1

**Additional context**

```
python3 -m venv .venv
source .venv/bin/activate
pip3 install fastapi-mvc
fastapi-mvc new videos-api
Traceback (most recent call last):
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/bin/fastapi-mvc", line 5, in <module>
    from fastapi_mvc.cli.cli import cli
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/fastapi_mvc/cli/cli.py", line 13, in <module>
    from fastapi_mvc.cli.run import run
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/fastapi_mvc/cli/run.py", line 14, in <module>
    from fastapi_mvc.utils import run_shell, get_poetry_path, require_fastapi_mvc_project
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/fastapi_mvc/utils/__init__.py", line 9, in <module>
    from fastapi_mvc.utils.generators import (
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/fastapi_mvc/utils/generators.py", line 11, in <module>
    from copier.user_data import load_answersfile_data
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/copier/main.py", line 28, in <module>
    from .errors import CopierAnswersInterrupt, ExtensionNotFoundError, UserMessageError
  File "/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/copier/errors.py", line 6, in <module>
    from pydantic.errors import _PathValueError
ImportError: cannot import name '_PathValueError' from 'pydantic.errors' (/Volumes/Projects/@9x3l6/videos-api/.venv/lib/python3.11/site-packages/pydantic/errors.py)
```

**Comment by rszamszur** [comment]
@9x3l6 Sorry for the late reply; I was on vacation :)

I do not own a mac at the moment, but I'll try to debug this. I'll make sure to keep you posted. 
In the meantime, try [installing from source using Poetry](https://fastapi-mvc.netlify.app/quickstart#from-source-with-poetry).

**Comment by andypickup-uni** [comment]
This could possibly be due to Pydantic 2 being installed, I've had this across 2 machines over the last few weeks when starting a new project.

Need to uninstall Pydantic v2 and install v1.10.13 and then this works. Not sure what the root of the issue is, whether somewhere in requirements it's just looking for latest. I haven't looked deep enough.

I'm running on PC through Docker with VSCode devcontainer on Python 3.11-bookworm. I think the other machine was using 3.10.

Hope this helps and someone can figure the issue out.

**Comment by chapmandu** [comment]
I can confirm I have the same issue on
- Ubuntu 22.04
- Python v3.10.12

```
code/python/myapp-fastapi 
❯ pip install fastapi-mvc
Collecting fastapi-mvc
  Downloading fastapi_mvc-0.28.1-py3-none-any.whl (23 kB)
Requirement already satisfied: click<8.2.0,>=8.1.3 in /usr/local/lib/python3.10/dist-packages (from fastapi-mvc) (8.1.7)
Requirement already satisfied: copier==6.2.0 in /usr/local/lib/python3.10/dist-packages (from fastapi-mvc) (6.2.0)
Requirement already satisfied: iteration_utilities>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (0.12.0)
Requirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (23.1)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (6.0.1)
Requirement already satisfied: questionary>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (2.0.1)
Requirement already satisfied: dunamai>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (1.19.0)
Requirement already satisfied: pyyaml-include>=1.2 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (1.3.2)
Requirement already satisfied: jinja2>=3.1.1 in /home/adam/.local/lib/python3.10/site-packages (from copier==6.2.0->fastapi-mvc) (3.1.2)
Requirement already satisfied: jinja2-ansible-filters>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (1.3.2)
Requirement already satisfied: colorama>=0.4.3 in /usr/lib/python3/dist-packages (from copier==6.2.0->fastapi-mvc) (0.4.4)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (0.11.2)
Requirement already satisfied: pygments>=2.7.1 in /home/adam/.local/lib/python3.10/site-packages (from copier==6.2.0->fastapi-mvc) (2.16.1)
Requirement already satisfied: pydantic>=1.10.2 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (2.5.3)
Requirement already satisfied: plumbum>=1.6.9 in /usr/local/lib/python3.10/dist-packages (from copier==6.2.0->fastapi-mvc) (1.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/adam/.local/lib/python3.10/site-packages (from jinja2>=3.1.1->copier==6.2.0->fastapi-mvc) (2.1.3)
Requirement already satisfied: pydantic-core==2.14.6 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.10.2->copier==6.2.0->fastapi-mvc) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.10.2->copier==6.2.0->fastapi-mvc) (4.7.1)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.10.2->copier==6.2.0->fastapi-mvc) (0.6.0)
Requirement already satisfied: prompt_toolkit<=3.0.36,>=2.0 in /usr/local/lib/python3.10/dist-packages (from questionary>=1.8.1->copier==6.2.0->fastapi-mvc) (3.0.36)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prompt_toolkit<=3.0.36,>=2.0->questionary>=1.8.1->copier==6.2.0->fastapi-mvc) (0.2.5)
Installing collected packages: fastapi-mvc
Successfully installed fastapi-mvc-0.28.1

code/python/myapp-fastapi 
❯ which fastapi-mvc
/usr/local/bin/fastapi-mvc

code/python/myapp-fastapi 
❯ fastapi-mvc --help
Traceback (most recent call last):
  File "/usr/local/bin/fastapi-mvc", line 5, in <module>
    from fastapi_mvc.cli.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/fastapi_mvc/cli/cli.py", line 13, in <module>
    from fastapi_mvc.cli.run import run
  File "/usr/local/lib/python3.10/dist-packages/fastapi_mvc/cli/run.py", line 14, in <module>
    from fastapi_mvc.utils import run_shell, get_poetry_path, require_fastapi_mvc_project
  File "/usr/local/lib/python3.10/dist-packages/fastapi_mvc/utils/__init__.py", line 9, in <module>
    from fastapi_mvc.utils.generators import (
  File "/usr/local/lib/python3.10/dist-packages/fastapi_mvc/utils/generators.py", line 11, in <module>
    from copier.user_data import load_answersfile_data
  File "/usr/local/lib/python3.10/dist-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/usr/local/lib/python3.10/dist-packages/copier/main.py", line 28, in <module>
    from .errors import CopierAnswersInterrupt, ExtensionNotFoundError, UserMessageError
  File "/usr/local/lib/python3.10/dist-packages/copier/errors.py", line 6, in <module>
    from pydantic.errors import _PathValueError
ImportError: cannot import name '_PathValueError' from 'pydantic.errors' (/usr/local/lib/python3.10/dist-packages/pydantic/errors.py)
```

**Comment by sbalasa** [comment]
This fixed the error on my Mac M1 chip:
`pip install pydantic==1.10.9`
